package com.example.socialmediacampaignagentsprintboot.model;

import dev.langchain4j.model.output.structured.Description;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a single post in a social media campaign, providing details
 * such as the targeted platform, audience, content theme, and associated
 * metadata for managing the post's lifecycle.
 * <p>
 * Properties:
 * - dayNumber: The sequential day number of the campaign (1-based index).
 * - platform: The targeted social media platform, such as LinkedIn or X.
 * - targetAudience: The intended audience demographic for this post.
 * - funnelStage: The marketing funnel stage this post aims to address.
 * - contentPillar: The strategic theme or category of the post's content.
 * - topicSummary: A concise description outlining the post's topic for copywriting.
 * - generatedContent: The finalized content text for the post, ready for publication.
 * - status: The current lifecycle status of the post, such as "pending," "drafted,"
 *   "rejected," or "approved."
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DailyPost {

        @Description("Day number relative to start (1 = Day 1)")
        private int dayNumber;

        @Description("The target social media platform (e.g., LinkedIn, X)")
        private Platform platform;

        @Description("Target audience for this post")
        private String targetAudience = "Young professionals";

        @Description("The marketing funnel stage this post targets")
        private FunnelStage funnelStage;

        @Description("The strategic theme of the content")
        private ContentPillar contentPillar;

        @Description("A brief description of what the post will be about (instructions for the copywriter)")
        private String topicSummary;

        @Description("The actual post content generated by the Copywriter Agent, ready for review and publishing")
        private String generatedContent = "";

        @Description("The status of the post (e.g., pending, drafted, rejected, approved)")
        private String status = "PENDING";
}