package com.example.socialmediacampaignagentsprintboot.model;

import dev.langchain4j.model.output.structured.Description;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class DailyPost {

        @Description("Day number relative to start (1 = Day 1)")
        private int dayNumber;

        @Description("The target social media platform (e.g., LinkedIn, X)")
        private Platform platform;

        @Description("The marketing funnel stage this post targets")
        private FunnelStage funnelStage;

        @Description("The strategic theme of the content")
        private ContentPillar contentPillar;

        @Description("A brief description of what the post will be about (instructions for the copywriter)")
        private String topicSummary;

        @Description("The actual post content generated by the Copywriter Agent, ready for review and publishing")
        private String generatedContent; // Holds the actual post content for human review
}