package com.example.socialmediacampaignagentsprintboot.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an audit record for a published post in a social media campaign.
 * This class provides metadata and details necessary for tracking,
 * analyzing, and evaluating the performance and alignment of a published post.
 * <p>
 * Fields:
 * - publishId: A unique identifier for the publishing event.
 * - campaignId: The campaign to which the published post belongs, useful for grouping related posts.
 * - dayNumber: The day in the campaign schedule when the post was published.
 * - timestamp: The exact time the post was published, formatted in ISO-8601.
 * - platform: The platform where the post was published, such as LinkedIn or X.
 * - funnelStage: The marketing funnel stage targeted by the post, for example, Awareness or Consideration.
 * - contentPillar: The thematic category or pillar of the content, such as Education or Promotion.
 * - targetAudience: The intended audience demographic for this post.
 * - content: The actual text content of the post generated by the AI.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class PublishedPostAudit {
    private String publishId;       // Unique ID for the publishing event
    private String campaignId;      // To group posts belonging to the same campaign
    private int dayNumber;          // The day in the schedule
    private String timestamp;       // ISO-8601 formatted time
    private String platform;        // LinkedIn, X, etc.
    private String funnelStage;     // Awareness, Consideration, etc.
    private String contentPillar;   // Education, Promotion, etc.
    private String targetAudience;  // Who this was written for
    private String content;         // The actual text generated by the AI
}