package com.example.socialmediacampaignagentsprintboot.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class PublishedPostAudit {
    private String publishId;       // Unique ID for the publishing event
    private String campaignId;      // To group posts belonging to the same campaign
    private int dayNumber;          // The day in the schedule
    private String timestamp;       // ISO-8601 formatted time
    private String platform;        // LinkedIn, X, etc.
    private String funnelStage;     // Awareness, Consideration, etc.
    private String contentPillar;   // Education, Promotion, etc.
    private String targetAudience;  // Who this was written for
    private String content;         // The actual text generated by the AI
}