package com.example.socialmediacampaignagentsprintboot.dto;

import com.example.socialmediacampaignagentsprintboot.model.ContentPillar;
import com.example.socialmediacampaignagentsprintboot.model.FunnelStage;
import com.example.socialmediacampaignagentsprintboot.model.Platform;
import dev.langchain4j.model.output.structured.Description;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object representing the daily post details in a social media campaign.
 * This class encapsulates the information needed for each scheduled post,
 * enabling interaction with and representation of specific marketing strategies.
 * <p>
 * Fields:
 * - dayNumber: Specifies the day number of the post relative to the campaign start (e.g., 1 = Day 1).
 * - platform: The target social media platform for the post (e.g., LinkedIn, X).
 * - funnelStage: The marketing funnel stage the post is designed to address (e.g., Awareness, Conversion).
 * - contentPillar: The strategic theme or pillar of the content (e.g., Education, Promotion).
 * - topicSummary: A short summary describing the topic or purpose of the post, intended as guidelines for copywriting.
 * - generatedContent: The content generated for the post, ready for review and publication.
 * - status: The current status of the post (e.g., Draft, Ready for Publishing).
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DailyPostDTO {
    @Description("Day number relative to start (1 = Day 1)")
    private int dayNumber;

    @Description("The target social media platform (e.g., LinkedIn, X)")
    private Platform platform;

    @Description("The marketing funnel stage this post targets")
    private FunnelStage funnelStage;

    @Description("The strategic theme of the content")
    private ContentPillar contentPillar;

    @Description("A brief description of what the post will be about (instructions for the copywriter)")
    private String topicSummary;

    @Description("The actual post content generated by the Copywriter Agent, ready for review and publishing")
    private String generatedContent;

    @Description("The status of the post")
    private String status;
}
